### ISSUE TITLE
can't connect router to tftp

### ISSUE THREAD

**Issue by Yahfz** [radix007/OpenWrt-Tp-Link-C6#3]
Can't get a connection in the TFTP, nothing shows in the log. Any ideas?

**Comment by NilsRo** [comment]
In my case it was Windows Firewall.

**Comment by jvaleros** [comment]
Any other ideas? I disabled the Windows Firewall in order to check if that was the issue. After pushing the reset button for 5 seconds, the far right LED lights up and stays on for about 10 seconds, but the TFTP server on my Windows 10 laptop is not detecting after setting the static IP to 192.168.0.66. As well as this, when I troubleshoot on Wireshark on the ETH interface it is only showing outgoing packages from my computer and no incoming ones. I am running out of ideas on what to check.

**Comment by radix007** [comment]
> Any other ideas? I disabled the Windows Firewall in order to check if that was the issue. After pushing the reset button for 5 seconds, the far right LED lights up and stays on for about 10 seconds, but the TFTP server on my Windows 10 laptop is not detecting after setting the static IP to 192.168.0.66. As well as this, when I troubleshoot on Wireshark on the ETH interface it is only showing outgoing packages from my computer and no incoming ones. I am running out of ideas on what to check.

Try Using Cat 6 cable , make sure that you are using 1000 Mbps  Full Duplex Connection And If that doesn't work then use a different laptop .

**Comment by radix007** [comment]
> Can't get a connection in the TFTP, nothing shows in the log. Any ideas?

Are you  using cat 5 or cat 6 ?  Also are you following the guide ? Make sure you install putty and configure it properly .
